In [1]:
import sys

sys.path.append("..")

import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
import time

from methods.kth.epssample import *
from methods.kth.fagin import *
from methods.kth.threshold import *
from methods.utils import *
from methods.range_search.hierarchy import *
from ranges.stripe_range import StripeRange

Test

In [2]:
dim = 2
k = 5
points = np.random.zipf(1.5, size=(20, dim))
weights = np.random.rand(dim)
# normalize wieghts
weights /= np.linalg.norm(weights)

In [3]:
fagins_algorithm(points, weights, k=k)

(array([ 2, 39]), np.float64(37.35638983920941))

In [4]:
find_kth_exhaustive(points, weights, k=k)

(array([ 2, 39]), np.float64(37.356389839209406))

In [5]:
threshold_algorithm(points, weights, k=k)

(array([ 2, 39]), np.float64(37.35638983920941))

In [6]:
def index_fn(points):
    ind = HierarchicalIndex(points, decay=4)
    ind.build_index()
    ind.find_coverage()
    ind.find_neighbor_stats()
    return ind


prep = preprocess(points, index_fn=index_fn, eps=1 / 32)

points[find_kth(*prep, weights=weights, k=k)]

L: 3
sample_size: 13 n: 20
3.25
Rank low: 2, Rank high: 4 (m=13)


array([[  1,  31],
       [  2,  39],
       [  4,  33],
       [141,  24]])

In [9]:
gt = find_kth_exhaustive(points, weights, k=k)

res = points[find_kth(*prep, weights=weights, k=k)]
gt[0] in res

3.25
Rank low: 2, Rank high: 4 (m=13)


True